server:
  port: 83
spring:
    # 数据源
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/testdb?useSSL=false&amp;characterEncoding=utf8
        username: root
        password: qb123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    # thymeleaf 视图配置
    thymeleaf:
        prefix: classpath:/views/
        suffix : .html
        cache: false

    devtools:
        livereload:
          enabled: true
#mybatis 配置文件和别名
mybatis:
    mapper-locations: classpath:mapping/*.xml
    type-aliases-package: com.example.springbootmybatis.model
#分页插件
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
